header:
  version: 16

distro: poky

defaults:
  repos:
    branch: kirkstone

repos:
  meta-morello:
    layers:
      meta-morello:
      meta-morello-toolchain:

  meta-arm:
    url: https://git.yoctoproject.org/meta-arm
    commit: c3e9fb12aa31d25e33d8392c4a233ed1275a3278
    layers:
      meta-arm:
      meta-arm-toolchain:

  poky:
    url: https://git.yoctoproject.org/git/poky
    commit: 2c05660b21c7cc1082aeac8b75d8a2d82e249f63
    layers:
      meta:
      meta-poky:

local_conf_header:
  base: |
    CONF_VERSION = "2"
  setup: |
    PACKAGE_CLASSES = "package_ipk"
    EXTRA_IMAGE_FEATURES:append = " debug-tweaks"

machine: unset

target:
  - core-image-minimal
