header:
  version: 16

distro: poky

defaults:
  repos:
    branch: scarthgap

repos:
  meta-morello:
    layers:
      meta-morello:
      meta-morello-toolchain:

  meta-arm:
    url: https://git.yoctoproject.org/meta-arm
    commit: a81c19915b5b9e71ed394032e9a50fd06919e1cd
    layers:
      meta-arm:
      meta-arm-toolchain:

  poky:
    url: https://git.yoctoproject.org/git/poky
    commit: b301218f4da7793624db3545efd8bf66888b77b0
    layers:
      meta:
      meta-poky:

local_conf_header:
  base: |
    CONF_VERSION = "2"
  setup: |
    PACKAGE_CLASSES = "package_ipk"
    EXTRA_IMAGE_FEATURES:append = " debug-tweaks"

machine: unset

target:
  - core-image-minimal
