BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	        ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS                     += "meta-morello-toolchain"
BBFILE_PATTERN_meta-morello-toolchain  := "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-morello-toolchain  = "5"

LAYERDEPENDS_meta-morello-toolchain = " \
    core \
"
LAYERSERIES_COMPAT_meta-morello-toolchain = "kirkstone"

PURECAP_SYSROOT_DIR ??= "/usr/lib/${GLOBAL_ARCH_TRIPLE}"

C64_ARCH_TRIPLE ??= "aarch64-linux-musl_purecap"
A64_ARCH_TRIPLE ??= "aarch64-linux-gnu"

A64_LIB_TRIPLE ??= "aarch64-unknown-linux-gnu"
C64_LIB_TRIPLE ??= "aarch64-unknown-linux-musl_purecap"

A64_ARCH_FLAGS ??= "-march=armv8"
C64_ARCH_FLAGS ??= "-march=morello -mabi=purecap"

GLOBAL_ARCH_TRIPLE ??= "${C64_ARCH_TRIPLE}"
GLOBAL_LIB_TRIPLE  ??= "${C64_LIB_TRIPLE}"
GLOBAL_ARCH_FLAGS  ??= "${C64_ARCH_FLAGS}"

MORELLO_ARCH       ??= "c64"
TOOLCHAIN          ??= "gnu"
MORELLO_TOOLCHAIN  ??= "gcc-morello"

LLVM_SHARED_SOURCE ??= "${TMPDIR}/work-shared/${MACHINE}/llvm-morello-source"

require conf/compiler/gcc-morello.conf
require conf/compiler/llvm-morello.conf