name: main

on:
  push:
    branches: 
      - scarthgap
    paths-ignore:
      - 'README.md'
      - '.github/workflows/release.yml'

  workflow_dispatch:

jobs:
   morello-soc:
      runs-on: the-capable-hub-aws-ci
      env:
         BUILD_DIR: ${{github.workspace}}/volatile/${{ github.job }}
      container:
        image: capablehub/cheri-yocto-morello:latest

      steps:
         - name: Setup
           run: |
              sudo mkdir -p ${{env.BUILD_DIR}}
              echo HOME=/home/ci | sudo tee -a $GITHUB_ENV
              sudo ln -sf /home/ci ${{env.BUILD_DIR}}
   
         - name: Checkout layers
           uses: actions/checkout@v5
           with:
              path: ${{env.BUILD_DIR}}
   
         - name: Build kas 
           run: |
            cd $BUILD_DIR
            KASFILES=$(ci/jobs-to-kas "${{ github.job }}")
            kas shell --update --force-checkout $KASFILES -c 'cat conf/*.conf'
            kas build $KASFILES

         - name: Upload build logs on failure
           if: failure()
           uses: actions/upload-artifact@v6
           with:
             name: failure-logs
             path: |
               ${{env.BUILD_DIR}}/build/tmp*/work*/**/temp/*.do_*.*

         - name: Upload wic artifacts
           uses: actions/upload-artifact@v6
           with:
              name: morello_artifacts_wic_${{ github.job }}
              path: |
                 ${{env.BUILD_DIR}}/build/tmp-soc/deploy/images/morello-soc/usb-image-morello-soc.wic

         - name: Upload fimrware artifacts
           uses: actions/upload-artifact@v6
           with:
              name: morello_artifacts_firmware_${{ github.job }}
              path: |
                 ${{env.BUILD_DIR}}/build/tmp-soc/deploy/images/morello-soc/board-firmware-sd-image.img

   morello-soc-test:
      name: "morello-soc hardware test"
      needs: morello-soc

      # Ensure we have access to the Morello board in The Capable Hub's farm
      runs-on: [ the-capable-hub-farm, board:Morello ]
      steps:
         - name: Check out repository
           uses: actions/checkout@v6

         - name: Download wic artifact
           uses: actions/download-artifact@v8
           with:
              name: morello_artifacts_wic_morello-soc

         - name: Download firmware artifact
           uses: actions/download-artifact@v8
           with:
              name: morello_artifacts_firmware_morello-soc

         - name: Flash firmware
           run: |
              sudo apt update && sudo apt install -y bmap-tools

              sudo usbrelay HURTM_1=0
              sudo dd if=board-firmware-sd-image.img of=/dev/disk/by-id/usb-ARM_M1SDP_500541683007-0:0
              sudo bmaptool copy --nobmap usb-image-morello-soc.wic /dev/disk/by-id/usb-SanDisk_Cruzer_Blade_00016104110624091916-0:0
              sync
              sudo usbrelay HURTM_1=1

         - name: Boot and test firmware
           shell: bash
           run: |
              cd ci/labgrid
              source /opt/labgrid-env/bin/activate

              stty -F /dev/ttyUSB0 115200
              echo -e "\n\nREBOOT" | sudo tee /dev/ttyUSB0
              sudo -E `which pytest` --lg-env local.yaml --capture=no test_shell.py

   morello-fvp:
      runs-on: the-capable-hub-aws-ci
      env:
         BUILD_DIR: ${{github.workspace}}/volatile/${{ github.job }}
      container:
        image: capablehub/cheri-yocto-morello:latest
      strategy:
        matrix:
          testing:
            - testimage

      steps:
         - name: Setup
           run: |
              sudo mkdir -p ${{env.BUILD_DIR}}
              echo HOME=/home/ci | sudo tee -a $GITHUB_ENV
              sudo ln -sf /home/ci ${{env.BUILD_DIR}}
      
         - name: Checkout layers
           uses: actions/checkout@v5
           with:
              path: ${{env.BUILD_DIR}}
   
         - name: Build kas 
           run: |
            cd $BUILD_DIR
            KASFILES=$(ci/jobs-to-kas "${{ github.job }}: [${{ matrix.testing }}]")
            echo $KASFILES
            kas shell --update --force-checkout $KASFILES -c 'cat conf/*.conf'
            kas build $KASFILES

         - name: Upload build logs on failure
           if: failure()
           uses: actions/upload-artifact@v6
           with:
             name: failure-logs
             path: |
               ${{env.BUILD_DIR}}/build/tmp*/work*/**/temp/*.do_*.*

         - name: Upload wic artifacts
           uses: actions/upload-artifact@v6
           with:
              name: morello_artifacts_wic_${{ github.job }}
              path: |
                 ${{env.BUILD_DIR}}/build/tmp-fvp/deploy/images/morello-fvp/usb-image-morello-fvp.wic

         - name: Upload firmware artifacts
           uses: actions/upload-artifact@v6
           with:
              name: morello_artifacts_firmware_${{ github.job }}
              path: |
                 ${{env.BUILD_DIR}}/build/tmp-fvp/deploy/images/morello-fvp/board-firmware-sd-image.img

   check-layers:
      runs-on: the-capable-hub-aws-ci
      env:
          BUILD_DIR: ${{github.workspace}}/volatile/${{ github.job }}
      container:
        image: capablehub/cheri-yocto-morello:latest

      strategy:
        matrix:
          layer:
            - meta-morello
            - meta-morello-toolchain
    
      steps:
        - name: Setup
          run: |
              sudo mkdir -p ${{env.BUILD_DIR}}
              echo HOME=/home/ci | sudo tee -a $GITHUB_ENV
              sudo ln -sf /home/ci ${{env.BUILD_DIR}}
   
        - name: Checkout layers
          uses: actions/checkout@v5
          with:
              path: ${{env.BUILD_DIR}}/${{ matrix.layer }} 
        
        - name: Check layer
          run: |
            layer_dir=${BUILD_DIR}/${{ matrix.layer }}
            cd ${layer_dir} 
            ls 
            echo ${layer_dir}
            kas shell --update --force-checkout ${layer_dir}/kas/base.yml --command \
              "yocto-check-layer-wrapper ${layer_dir}/${{ matrix.layer }} -n --dependency ${layer_dir}/meta-* ${layer_dir}/meta-arm/meta-arm ${layer_dir}/meta-arm/meta-arm-toolchain"