name: release

on:
  push:
    tags:
      - v2*

  workflow_dispatch:

permissions:
  contents: read

jobs:
   morello-soc:
      runs-on: the-capable-hub-aws-ci
      env:
         BUILD_DIR: ${{github.workspace}}/volatile/${{ github.job }}
         RELEASE_DIR: ${{github.workspace}}/volatile/${{ github.job }}/release
      container:
        image: capablehub/cheri-yocto-morello:latest

      steps:
         - name: Setup
           run: |
              mkdir -p "$BUILD_DIR"

              echo HOME=/home/ci | sudo tee -a $GITHUB_ENV
              ln -sf /home/ci "$BUILD_DIR"
          
              sudo apt-get install -y less curl gpg zip

         - name: Checkout layers
           uses: actions/checkout@v5
           with:
              path: ${{env.BUILD_DIR}}

         - name: Setup AWS
           run: | 

              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

              curl -o awscliv2.sig https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip.sig

              gpg --import "$BUILD_DIR"/ci/awsclikey
              gpg --verify awscliv2.sig awscliv2.zip

              unzip awscliv2.zip
              sudo ./aws/install   

              aws --version
   
         - name: Build kas 
           run: |
            cd "$BUILD_DIR"
            KASFILES=$(ci/jobs-to-kas "${{ github.job }}")
            kas shell --update --force-checkout $KASFILES -c 'cat conf/*.conf'
            kas build $KASFILES

         - name: Upload build logs on failure
           if: failure()
           uses: actions/upload-artifact@v6
           with:
             name: failure-logs
             path: |
               ${{env.BUILD_DIR}}/build/tmp*/work*/**/temp/*.do_*.*

         - name: Stage for upload
           run: |
              mkdir -p "$RELEASE_DIR"

              cp -L "$BUILD_DIR/build/tmp-soc/deploy/images/morello-soc/usb-image-morello-soc.wic" "$RELEASE_DIR"

              cp "$BUILD_DIR/build/tmp-soc/deploy/images/morello-soc/board-firmware-sd-image.img" "$RELEASE_DIR"

         - name: Upload release
           env:
             AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
             AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
             AWS_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
             AWS_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
           shell: bash
           run: |
              # Get pushed tag/branch name
              # https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions
              VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
              [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

              RELEASE_NAME="morello-release-$VERSION"
              aws s3 sync "$RELEASE_DIR" "s3://$AWS_BUCKET_NAME/$RELEASE_NAME" --endpoint-url $AWS_ENDPOINT --region auto
                
